create table if not exists rating_mpaa
(
    rating_mpaa_id integer generated by default as identity primary key,
    name varchar(100) NOT NULL
);

create table if not exists genre
(
    genre_id integer generated by default as identity primary key,
    name varchar(100) NOT NULL
);

create table if not exists film
(
    film_id long generated by default as identity primary key,
    name varchar(100),
    description varchar(255),
    release_date date,
    duration long,
    rating_mpaa_id integer,
    is_delete boolean default false
);

create table if not exists film_genre
(
    film_id long references film (film_id),
    genre_id integer references genre (genre_id)
);

create table if not exists users
(
    user_id long generated by default as identity primary key,
    email varchar(100) UNIQUE,
    login varchar(100) UNIQUE,
    name varchar(100),
    birthday date,
    is_delete boolean default false
);

create table if not exists user_film_likes
(
    user_id long references users (user_id),
    film_id integer references film (film_id)
);

create table if not exists friendship
(
    friendship_id long generated by default as identity primary key,
    user_id long references users (user_id),
    friend_id long references users (user_id),
    confirmed boolean
);

create unique index if not exists user_film_likes_uindex
    on user_film_likes (user_id, film_id);

create unique index if not exists film_genre_uindex
    on film_genre (film_id, genre_id);

create index if not exists film_index_name
    on film (name);

create table if not exists review
(
    review_id long generated by default as identity primary key,
    content text,
    is_positive boolean,
    user_id long references users (user_id),
    film_id long references film (film_id),
    is_delete boolean default false
);

create table if not exists review_likes
(
    review_likes_id long generated by default as identity primary key,
    review_id long references review (review_id),
    user_id long references users (user_id),
    is_like boolean,
    is_delete boolean default false
);

create table if not exists feed
(
    event_id   long generated by default as identity primary key,
    user_id    long references users (user_id),
    event_type varchar(50),
    operation  varchar(50),
    timestamp  long,
    entity_id  long,
    CHECK (event_type = 'LIKE' OR event_type = 'REVIEW' OR event_type = 'FRIEND'),
    CHECK (operation = 'ADD' OR operation = 'UPDATE' OR operation = 'REMOVE')
);